/* Generado por generar-palabras.mjs — NO editar a mano. */
window.WORDS = [{"w":"posta","cat":"catchphrase","hint":"Cuando jurás que no estás chamuyando.","disp":"posta"},
{"w":"nono","cat":"catchphrase","hint":"Negativa tan firme que sale repetida.","disp":"nono"},
{"w":"sisi","cat":"catchphrase","hint":"Un 'sí' tan convencido que va duplicado.","disp":"sisi"},
{"w":"apoyo","cat":"catchphrase","hint":"Lo que ange jura dar siempre, incondicional.","disp":"apoyo"},
{"w":"ahre","cat":"catchphrase","hint":"El seguro que ponés para que no te crean del todo.","disp":"ahre"},
{"w":"gede","cat":"catchphrase","hint":"El que no afloja ni cuando le pedís que afloje.","disp":"gede"},
{"w":"wordle","cat":"catchphrase","hint":"Lo que estás haciendo en este preciso momento.","disp":"wordle"},
{"w":"letal","cat":"catchphrase","hint":"El 10 de puntaje, sin escalas.","disp":"letal"},
{"w":"mistiva","cat":"catchphrase","hint":"Quiso ser 'mística' y nació un clásico (28/4).","disp":"mistiva"},
{"w":"downcito","cat":"catchphrase","hint":"El ritual de la medianoche, en chiquito.","disp":"downcito"},
{"w":"perobueno","cat":"frase","hint":"El suspiro hecho palabra para cambiar de tema.","disp":"pero bueno"},
{"w":"queseyo","cat":"frase","hint":"El encogimiento de hombros, en tres palabras.","disp":"que se yo"},
{"w":"nadaquever","cat":"frase","hint":"Cuando metés algo que no pinta para nada con el tema.","disp":"nada que ver"},
{"w":"andaasaber","cat":"frase","hint":"El misterio sin resolver, dicho al pasar.","disp":"anda a saber"},
{"w":"ojolacall","cat":"frase","hint":"Counter: no te duermas en la comunicación.","disp":"ojo la call"},
{"w":"apoyolacall","cat":"frase","hint":"Bancar al equipo, pero con los auriculares puestos.","disp":"apoyo la call"},
{"w":"apoyenahi","cat":"frase","hint":"Counter: '¡vengan que no aguanto!'","disp":"apoyen ahi"},
{"w":"esletal","cat":"frase","hint":"El veredicto de dos palabras cuando algo es tremendo.","disp":"es letal"},
{"w":"miticalacall","cat":"frase","hint":"Esa jugada hablada que se cuenta como leyenda.","disp":"mitica la call"},
{"w":"gorda","cat":"cariño","hint":"El apodo que ella banca... a medias.","disp":"gorda"},
{"w":"gordo","cat":"cariño","hint":"El apodo cariñoso, versión de él.","disp":"gordo"},
{"w":"amor","cat":"cariño","hint":"El apodo número uno, sin vueltas.","disp":"amor"},
{"w":"linda","cat":"cariño","hint":"Piropo básico: que es bonita.","disp":"linda"},
{"w":"besos","cat":"cariño","hint":"Con los que se cierra un mensaje.","disp":"besos"},
{"w":"beso","cat":"cariño","hint":"Cariño en la boca, de a uno.","disp":"beso"},
{"w":"abrazo","cat":"cariño","hint":"Apretón de oso.","disp":"abrazo"},
{"w":"extraño","cat":"cariño","hint":"Lo que pasa cuando el otro no está.","disp":"extraño"},
{"w":"viernes","cat":"mundo","hint":"El día más esperado de la semana.","disp":"viernes"},
{"w":"faceit","cat":"mundo","hint":"El ring online donde ange sufre al Counter.","disp":"faceit"},
{"w":"laburo","cat":"mundo","hint":"Lo que arruina los lunes.","disp":"laburo"},
{"w":"uber","cat":"mundo","hint":"El taxi que no es taxi.","disp":"uber"},
{"w":"tiktok","cat":"mundo","hint":"El pozo sin fondo de videos verticales.","disp":"tiktok"},
{"w":"cine","cat":"mundo","hint":"Pantalla gigante, pochoclos y oscuridad.","disp":"cine"},
{"w":"bonzi","cat":"mundo","hint":"Un barrio.","disp":"bonzi"},
{"w":"subte","cat":"mundo","hint":"El que va apurado y nunca ve el sol.","disp":"subte"},
{"w":"crunchy","cat":"mundo","hint":"Esa risa: jeje.","disp":"crunchy"},
{"w":"insta","cat":"mundo","hint":"La de las fotos, en corto.","disp":"insta"},
{"w":"reels","cat":"mundo","hint":"El idioma oficial de esta pareja.","disp":"reels"},
{"w":"facu","cat":"mundo","hint":"Donde se rinde y se sufre.","disp":"facu"},
{"w":"hamburguesa","cat":"mundo","hint":"Lo que pide el que NO quiere ensalada.","disp":"hamburguesa"},
{"w":"discord","cat":"mundo","hint":"El bar virtual con micrófono.","disp":"discord"},
{"w":"tinder","cat":"mundo","hint":"Donde se desliza buscando el match.","disp":"tinder"},
{"w":"perfume","cat":"mundo","hint":"Lo que te tirás para no oler a humano.","disp":"perfume"},
{"w":"sushi","cat":"mundo","hint":"El que se come con palitos.","disp":"sushi"},
{"w":"tostado","cat":"mundo","hint":"Jamón y queso bien apretado y caliente (¡NO en femenino!).","disp":"tostado"},
{"w":"casancrem","cat":"mundo","hint":"El primo argentino del Philadelphia.","disp":"casancrem"},
{"w":"franui","cat":"mundo","hint":"Frambuesa con saquito de chocolate, del freezer.","disp":"franui"},
{"w":"mostaza","cat":"mundo","hint":"La amarilla que va sí o sí en el tostado.","disp":"mostaza"},
{"w":"delivery","cat":"mundo","hint":"Cuando ganó la fiaca y perdió la cocina.","disp":"delivery"},
{"w":"caballito","cat":"mundo","hint":"Suena a juguete pero es un barrio porteño.","disp":"caballito"},
{"w":"merengues","cat":"mundo","hint":"Nubes dulces que se desarman en la boca.","disp":"merengues"},
{"w":"counterstrike","cat":"mundo","hint":"Donde se grita 'rush B' y ange sufre.","disp":"counter strike"},
{"w":"cs","cat":"mundo","hint":"El shooter de 'rush B', en siglas.","disp":"cs"},
{"w":"sushilibre","cat":"mundo","hint":"Japonés con palitos, pero sin freno ni límite.","disp":"sushi libre"},
{"w":"lahaine","cat":"mundo","hint":"Cine francés, blanco y negro, mucho bardo.","disp":"la haine"},
{"w":"instagram","cat":"mundo","hint":"La de las fotos, nombre completo.","disp":"instagram"},
{"w":"nomas","cat":"slang","hint":"Sin tanta vuelta, así de simple.","disp":"nomas"},
{"w":"corte","cat":"slang","hint":"Muletilla que reemplaza a 'o sea'.","disp":"corte"},
{"w":"boluda","cat":"slang","hint":"'Che' para una amiga.","disp":"boluda"},
{"w":"quiza","cat":"slang","hint":"Ni sí ni no.","disp":"quiza"},
{"w":"mierda","cat":"slang","hint":"La puteada más versátil que hay.","disp":"mierda"},
{"w":"olvidate","cat":"slang","hint":"Puede ser 'jamás' o 'obvio', según cómo lo digas.","disp":"olvidate"},
{"w":"boludo","cat":"slang","hint":"'Che' para un amigo.","disp":"boludo"},
{"w":"piola","cat":"slang","hint":"Ni denso ni quilombero: re tranqui.","disp":"piola"},
{"w":"toque","cat":"slang","hint":"Ni mucho ni poco, una pizca.","disp":"toque"},
{"w":"tranqui","cat":"slang","hint":"Mensaje para el nervioso: bajá un cambio.","disp":"tranqui"},
{"w":"terrible","cat":"slang","hint":"El que agranda todo cuando exagera.","disp":"terrible"},
{"w":"joda","cat":"slang","hint":"Puede ser un chiste o una previa.","disp":"joda"},
{"w":"bue","cat":"slang","hint":"El 'bueno' de los que ya no tienen ganas.","disp":"bue"},
{"w":"paja","cat":"slang","hint":"Las ganas de no hacer absolutamente nada.","disp":"paja"},
{"w":"pedilo","cat":"slang","hint":"Insistir para que te lo den, como el día 1.","disp":"pedilo"},
{"w":"ponele","cat":"slang","hint":"Muletilla para suponer algo al azar.","disp":"ponele"},
{"w":"down","cat":"slang","hint":"Estar de bajón; o el saludo de la noche.","disp":"down"},
{"w":"chabon","cat":"slang","hint":"Un fulano cualquiera.","disp":"chabon"},
{"w":"full","cat":"slang","hint":"A tope, hasta las manos.","disp":"full"},
{"w":"orto","cat":"slang","hint":"La mala suerte, o el traste.","disp":"orto"},
{"w":"manija","cat":"slang","hint":"Cuando no podés parar de pensar en algo que se viene.","disp":"manija"},
{"w":"carajo","cat":"slang","hint":"A donde mandás lo que te molesta.","disp":"carajo"},
{"w":"celu","cat":"slang","hint":"Lo que mirás 200 veces por día.","disp":"celu"},
{"w":"banco","cat":"slang","hint":"Donde se guarda la plata; también es apoyar a alguien.","disp":"banco"},
{"w":"banca","cat":"slang","hint":"El asiento largo de la plaza; o aguantar un toque.","disp":"banca"},
{"w":"peli","cat":"slang","hint":"Lo que se ve un viernes en el sillón.","disp":"peli"},
{"w":"crack","cat":"slang","hint":"El que la rompe toda.","disp":"crack"},
{"w":"boludez","cat":"slang","hint":"Una pavada que no vale la pena.","disp":"boludez"},
{"w":"cheto","cat":"slang","hint":"El que toma agua con gas en restó caro.","disp":"cheto"},
{"w":"villero","cat":"slang","hint":"De barrio humilde, lo opuesto a careta.","disp":"villero"},
{"w":"choto","cat":"slang","hint":"Lo más lejos posible de buenísimo.","disp":"choto"},
{"w":"flashe","cat":"slang","hint":"Cuando tu cabeza inventa una película entera.","disp":"flashe"},
{"w":"pesimo","cat":"slang","hint":"La nota más baja de todas.","disp":"pesimo"},
{"w":"kai","cat":"nombre","hint":"Ella, fuego en el pelo.","disp":"kai"},
{"w":"angelo","cat":"nombre","hint":"Él, con nombre casi de santo.","disp":"angelo"},
{"w":"maxi","cat":"nombre","hint":"Del grupo.","disp":"maxi"},
{"w":"ange","cat":"nombre","hint":"Él, como lo llama ella.","disp":"ange"},
{"w":"rafa","cat":"nombre","hint":"Del grupo (suena a tortuga ninja).","disp":"rafa"},
{"w":"kevin","cat":"nombre","hint":"Del grupo (el de 'mi pobre angelito').","disp":"kevin"},
{"w":"tobi","cat":"nombre","hint":"Del grupo de amigos.","disp":"tobi"},
{"w":"roman","cat":"nombre","hint":"Del grupo (a Riquelme le gustaría).","disp":"roman"},
{"w":"vana","cat":"nombre","hint":"Del grupo de amigas.","disp":"vana"},
{"w":"liam","cat":"nombre","hint":"El cantante de Oasis.","disp":"liam"},
{"w":"baba","cat":"nombre","hint":"Lo que chorrea de la boca de un bebé dormido.","disp":"baba"},
{"w":"skipper","cat":"nombre","hint":"El de Madagascar.","disp":"skipper"},
{"w":"kuchi","cat":"nombre","hint":"Del grupo de amigos.","disp":"kuchi"},
{"w":"ana","cat":"nombre","hint":"La mamá.","disp":"ana"},
{"w":"fabri","cat":"nombre","hint":"El hermano.","disp":"fabri"},
{"w":"beni","cat":"nombre","hint":"Del grupo de amigos.","disp":"beni"},
{"w":"leon","cat":"nombre","hint":"El rey de la selva.","disp":"leon"},
{"w":"peni","cat":"nombre","hint":"Del grupo de amigos.","disp":"peni"},
{"w":"puta","cat":"insulto","hint":"La madre que más se nombra al putear.","disp":"puta"},
{"w":"culo","cat":"insulto","hint":"Con lo que te caés sentado.","disp":"culo"},
{"w":"mogolica","cat":"insulto","hint":"Insulto re incorrecto para una tonta.","disp":"mogolica"},
{"w":"negro","cat":"insulto","hint":"Color oscuro... o piropo/insulto según el barrio.","disp":"negro"},
{"w":"mogolico","cat":"insulto","hint":"Insulto re incorrecto para un tonto.","disp":"mogolico"},
{"w":"imbecil","cat":"insulto","hint":"Un boludo, pero con diploma.","disp":"imbecil"},
{"w":"nazi","cat":"insulto","hint":"El del bigotito chiquito y el saludo con el brazo.","disp":"nazi"},
{"w":"gay","cat":"insulto","hint":"Lo que angelo claramente no es 😏","disp":"gay"},
{"w":"trola","cat":"insulto","hint":"Una a la que le gusta salir... bastante.","disp":"trola"},
{"w":"forra","cat":"insulto","hint":"Una atorranta de manual.","disp":"forra"},
{"w":"pija","cat":"sexual","hint":"El amigo del hombre que no es el perro.","disp":"pija"},
{"w":"concha","cat":"sexual","hint":"Caracol de mar... o no tanto.","disp":"concha"},
{"w":"verga","cat":"sexual","hint":"Lo que cuelga entre las piernas del hombre.","disp":"verga"},
{"w":"cojer","cat":"sexual","hint":"Sexo, escrito con falta de ortografía a propósito.","disp":"cojer"},
{"w":"chupala","cat":"sexual","hint":"Una orden... para que se agachen.","disp":"chupala"},
{"w":"garchar","cat":"sexual","hint":"Lo que se hace en la cama y no es dormir (bien argento).","disp":"garchar"},
{"w":"teta","cat":"sexual","hint":"Chupones.","disp":"teta"},
{"w":"condon","cat":"sexual","hint":"El que evita sorpresas de nueve meses.","disp":"condon"},
{"w":"apelo","cat":"sexual","hint":"Sin gomita, a lo bestia.","disp":"apelo"},
{"w":"perro","cat":"chat","hint":"El que te recibe moviendo la cola.","disp":"perro"},
{"w":"uvas","cat":"chat","hint":"Las que se comen de a doce en Año Nuevo.","disp":"uvas"},
{"w":"llorar","cat":"chat","hint":"Lo que provocan las cebollas y las pelis tristes.","disp":"llorar"},
{"w":"premier","cat":"chat","hint":"El modo ranqueado del Counter (o un estreno).","disp":"premier"},
{"w":"lock","cat":"chat","hint":"Cerrar con llave en inglés; o concentrarse a full.","disp":"lock"},
{"w":"match","cat":"chat","hint":"Una partida... o el flechazo mutuo en una app.","disp":"match"},
{"w":"lit","cat":"meme","hint":"Algo que está que arde (inglés).","disp":"lit"},
{"w":"mid","cat":"meme","hint":"El 5 de calificación: ni fu ni fa.","disp":"mid"},
{"w":"aura","cat":"meme","hint":"El 'campo de energía' que ganás o perdés según el papelón.","disp":"aura"},
{"w":"hard","cat":"meme","hint":"Cuando algo le mete con todo (inglés: duro).","disp":"hard"},
{"w":"bro","cat":"meme","hint":"El 'hermano' del gif de Jonah Hill.","disp":"bro"},
{"w":"chill","cat":"meme","hint":"El modo relax (inglés).","disp":"chill"},
{"w":"peak","cat":"meme","hint":"La cima, el punto más alto (inglés).","disp":"peak"},
{"w":"banger","cat":"meme","hint":"Un temazo que no falla.","disp":"banger"},
{"w":"goat","cat":"meme","hint":"Siglas del mejor de la historia (y un animal con cuernos).","disp":"goat"},
{"w":"lowk","cat":"meme","hint":"Medio en secreto, un poquito.","disp":"lowk"},
{"w":"meme","cat":"meme","hint":"El chiste con imagen que circula por todos lados.","disp":"meme"},
{"w":"clean","cat":"meme","hint":"Algo prolijo, sin una mancha (inglés).","disp":"clean"},
{"w":"ultra","cat":"meme","hint":"El prefijo de los exagerados.","disp":"ultra"},
{"w":"sus","cat":"meme","hint":"Sospechoso (lo gritaban en el Among Us).","disp":"sus"},
{"w":"vibe","cat":"meme","hint":"La energía que transmite algo.","disp":"vibe"},
{"w":"slay","cat":"meme","hint":"Cuando la reventás toda.","disp":"slay"},
{"w":"cooked","cat":"meme","hint":"Cuando ya fuiste, estás frito (inglés).","disp":"cooked"},
{"w":"ick","cat":"meme","hint":"El detalle mínimo que te mata el deseo.","disp":"ick"},
{"w":"rizz","cat":"meme","hint":"El don para chamuyar.","disp":"rizz"},
{"w":"cringe","cat":"meme","hint":"La vergüenza que sentís POR otro.","disp":"cringe"},
{"w":"fym","cat":"meme","hint":"Sigla de incredulidad: '¿cómo que...?'","disp":"fym"},
{"w":"ngl","cat":"meme","hint":"Sigla para arrancar siendo sincero.","disp":"ngl"},
{"w":"highk","cat":"meme","hint":"Lo contrario de disimular: a la vista de todos.","disp":"highk"},
{"w":"icl","cat":"meme","hint":"Sigla de 'no te puedo mentir'.","disp":"icl"},
{"w":"wyd","cat":"meme","hint":"Sigla del clásico '¿qué hacés?'","disp":"wyd"},
{"w":"iguessbro","cat":"meme","hint":"El gif de Jonah Hill resignado, frotándose el ojo.","disp":"i guess bro"}];
